export const APPWRITE_CONFIG = {
  endpoint: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT,
  projectId: process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID,
  databaseId: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID,
  bucketId: process.env.NEXT_PUBLIC_BUCKET_ID,
  postsCollectionId: process.env.NEXT_PUBLIC_POSTS_COLLECTION_ID,
  pagesCollectionId: process.env.NEXT_PUBLIC_PAGES_COLLECTION_ID,
  categoriesCollectionId: process.env.NEXT_PUBLIC_CATEGORIES_COLLECTION_ID,
  servicesCollectionId: process.env.NEXT_PUBLIC_SERVICES_COLLECTION_ID,
  leadsCollectionId: process.env.NEXT_PUBLIC_LEADS_COLLECTION_ID,
  settingsCollectionId: process.env.NEXT_PUBLIC_SETTINGS_COLLECTION_ID,
  seoCollectionId: process.env.NEXT_PUBLIC_SEO_COLLECTION_ID,
  homepageCollectionId: process.env.NEXT_PUBLIC_HOMEPAGE_COLLECTION_ID,
  homepageFaqCollectionId: process.env.NEXT_PUBLIC_HOMEPAGE_FAQS_COLLECTION_ID,
  homepageServicesCollectionId: process.env.NEXT_PUBLIC_HOMEPAGE_SERVICES_COLLECTION_ID,
  homepageBrandsCollectionId: process.env.NEXT_PUBLIC_HOMEPAGE_BRANDS_COLLECTION_ID,
  homepageFeaturesCollectionId: process.env.NEXT_PUBLIC_HOMEPAGE_FEATURES_COLLECTION_ID,
  homepageWhyChooseCollectionId: process.env.NEXT_PUBLIC_HOMEPAGE_WHY_CHOOSE_COLLECTION_ID,
  homepageResultsCollectionId: process.env.NEXT_PUBLIC_HOMEPAGE_RESULTS_COLLECTION_ID,
  homepageProcessCollectionId: process.env.NEXT_PUBLIC_HOMEPAGE_PROCESS_COLLECTION_ID,
  homepageCtaCollectionId: process.env.NEXT_PUBLIC_HOMEPAGE_CTA_COLLECTION_ID,
  homepageContactCollectionId: process.env.NEXT_PUBLIC_HOMEPAGE_CONTACT_COLLECTION_ID,
};